services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: snapnet_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    depends_on:
      - db
    networks:
      - snapnet_app_network

  db:
    image: mariadb:latest
    container_name: snapnet_app_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - snapnet_app_network

  nginx:
    image: nginx:latest
    container_name: snapnet_app_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - snapnet_app_network
        
  phpmyadmin:
    image: lscr.io/linuxserver/phpmyadmin:latest
    container_name: snapnet_app_phpmyadmin
    restart: unless-stopped
    ports:
      - "8088:80"
    environment:
      PMA_HOST: snapnet_app_db
      PMA_USER: ${DB_USERNAME}
      PMA_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - db
    networks:
      - snapnet_app_network

networks:
  snapnet_app_network:

volumes:
  mysql_data:
